"""Tests for retained Nsight report validation."""

from __future__ import annotations

from pathlib import Path

import pytest

from scripts.validate_ncu_capability import validate_capability
from scripts.validate_profiler_outputs import validate_profiles, validate_summary


def test_profiler_summaries_require_kernel_and_numeric_measurements(tmp_path: Path) -> None:
    nsys = tmp_path / "nsys.csv"
    ncu = tmp_path / "ncu.csv"
    nsys.write_text(
        "Generated by Nsight Systems\n"
        "Time (%),Total Time (ns),Instances,Name\n"
        '10.5,1250,1,"residualRmsNormFloat4(float*)"\n',
        encoding="utf-8",
    )
    ncu.write_text(
        "==PROF== Disconnected from process\n"
        "ID,Process ID,Kernel Name,Metric Name,Metric Unit,Metric Value\n"
        '1,99,"residualRmsNormFloat4(float*)",SM Frequency,cycle/nsecond,1.25\n',
        encoding="utf-8",
    )
    reports = [
        tmp_path / name for name in ("timeline.nsys-rep", "timeline.sqlite", "kernel.ncu-rep")
    ]
    for path in reports:
        path.write_bytes(b"retained")

    value = validate_profiles(
        nsys_summary=nsys,
        ncu_summary=ncu,
        nsys_report=reports[0],
        nsys_sqlite=reports[1],
        ncu_report=reports[2],
    )

    assert value["status"] == "passed"
    assert value["primary_performance_gate"] is False


def test_profile_banner_and_text_only_kernel_rows_fail_closed(tmp_path: Path) -> None:
    path = tmp_path / "profile.csv"
    path.write_text("TensorRT Release residualRmsNormFloat4,1\n", encoding="utf-8")
    with pytest.raises(RuntimeError, match="contains a banner"):
        validate_summary(path, summary_kind="nsys")
    path.write_text("Time (%),Name\nunavailable,residualRmsNormFloat4\n", encoding="utf-8")
    with pytest.raises(RuntimeError, match="no finite"):
        validate_summary(path, summary_kind="nsys")


def test_profile_summary_rejects_ids_malformed_headers_and_nan(tmp_path: Path) -> None:
    path = tmp_path / "profile.csv"
    path.write_text(
        "ID,Process ID,Kernel Name,Metric Name,Metric Value\n"
        "7,99,residualRmsNormFloat4,SM Frequency,unavailable\n",
        encoding="utf-8",
    )
    with pytest.raises(RuntimeError, match="no finite"):
        validate_summary(path, summary_kind="ncu")
    path.write_text("ID,Process ID,Kernel Name\n7,99,residualRmsNormFloat4\n", encoding="utf-8")
    with pytest.raises(RuntimeError, match="no recognized ncu measurement header"):
        validate_summary(path, summary_kind="ncu")
    path.write_text(
        "Kernel Name,Metric Name,Metric Value\nresidualRmsNormFloat4,SM Frequency,NaN\n",
        encoding="utf-8",
    )
    with pytest.raises(RuntimeError, match="no finite"):
        validate_summary(path, summary_kind="ncu")


def test_counter_capability_is_explicitly_non_diagnostic(tmp_path: Path) -> None:
    summary = tmp_path / "capability.csv"
    summary.write_text(
        "Kernel Name,Metric Name,Metric Value\nresidualRmsNormFloat4,SM Frequency,1.5\n",
        encoding="utf-8",
    )
    report = tmp_path / "capability.ncu-rep"
    report.write_bytes(b"retained")

    value = validate_capability(summary=summary, report=report)

    assert value["status"] == "passed"
    assert value["counter_permission_verified"] is True
    assert value["primary_performance_gate"] is False
    assert value["diagnostic_profile"] is False


def test_empty_binary_report_fails_closed(tmp_path: Path) -> None:
    summary = tmp_path / "summary.csv"
    summary.write_text("Name,Time\nresidualRmsNormFloat4,1\n", encoding="utf-8")
    empty = tmp_path / "empty.ncu-rep"
    empty.touch()
    with pytest.raises(RuntimeError, match="absent or empty"):
        validate_profiles(
            nsys_summary=summary,
            ncu_summary=summary,
            nsys_report=empty,
            nsys_sqlite=empty,
            ncu_report=empty,
        )
