"""Checked-in schema parity tests."""

from __future__ import annotations

import json
from pathlib import Path

from upgrade_guard.contracts.build import BuildManifest
from upgrade_guard.contracts.bundle import BundleManifest
from upgrade_guard.contracts.case import CaseManifest
from upgrade_guard.contracts.doctor import DoctorResult
from upgrade_guard.contracts.environment import EnvironmentLock, MatrixLock
from upgrade_guard.contracts.matrix import MatrixSpec
from upgrade_guard.contracts.qualification import QualificationSpec
from upgrade_guard.contracts.reference_environment import ReferenceEnvironmentLock
from upgrade_guard.contracts.results import RunResult
from upgrade_guard.corpus.registry import CorpusLock, CorpusRecipe
from upgrade_guard.reduce.predicate import ReductionRequest
from upgrade_guard.report.model import ReportModel

ROOT = Path(__file__).resolve().parents[2]


def test_checked_in_schemas_match_contracts() -> None:
    models = {
        "build.schema.json": BuildManifest,
        "bundle.schema.json": BundleManifest,
        "case.schema.json": CaseManifest,
        "corpus-lock.schema.json": CorpusLock,
        "corpus-recipe.schema.json": CorpusRecipe,
        "doctor.schema.json": DoctorResult,
        "environment-lock.schema.json": EnvironmentLock,
        "matrix-lock.schema.json": MatrixLock,
        "matrix.schema.json": MatrixSpec,
        "qualification.schema.json": QualificationSpec,
        "reference-environment-lock.schema.json": ReferenceEnvironmentLock,
        "reduction-request.schema.json": ReductionRequest,
        "report.schema.json": ReportModel,
        "result.schema.json": RunResult,
    }
    for name, model in models.items():
        stored = json.loads((ROOT / "schemas" / name).read_text(encoding="utf-8"))
        expected = model.model_json_schema()
        comment = stored.pop("$comment")
        assert comment == "Generated by scripts/generate_schemas.py. Do not edit manually."
        assert stored == expected
    assert {path.name for path in (ROOT / "schemas").glob("*.schema.json")} == set(models)


def test_every_schema_forbids_unknown_fields() -> None:
    for schema in (ROOT / "schemas").glob("*.schema.json"):
        document = json.loads(schema.read_text(encoding="utf-8"))
        assert document["additionalProperties"] is False
